### ISSUE TITLE
Spell Descriptions / Cast need to take into account action symbols

### ISSUE THREAD

**Issue by jrmiller82** [fyjham-ts/Pathfinder-2E-Spell-DB#14]
For example "Heal" https://2e.aonprd.com/Spells.aspx?ID=148 needs to show the separate action numbers and not just the verbal, material, etc... Perhaps using a unicode character to replace the icons?

**Comment by fyjham-ts** [comment]
Thanks for the feedback. Have gone through and found all the spells with a range of actions like heal and checked to see if any icons were missed in the scrape. Fixed up heal, harm, heal animal and wild morph. Used the unicode ◈ symbol for actions as used in rest of app (currently my understanding is the actual icons aren't allowed to be used cause they're not in Paizo's community use pack yet).

These fixes should go live with v1.0.6 (Hoping to do another release this weekend).
