### ISSUE TITLE
Repulsion Range should be "Emanation up to 40feet"

### ISSUE THREAD

**Issue by jrmiller82** [fyjham-ts/Pathfinder-2E-Spell-DB#16]

**Comment by fyjham-ts** [comment]
Looking at this it appears to be already listing "emanation up to 40-feet". I've removed the hyphen for a space, but not sure that's what you were referring to here?

**Comment by jrmiller82** [comment]
Hmmm. In the json data I looked at it just says “emanation” for that field.

**Comment by fyjham-ts** [comment]
Double checked: https://github.com/fyjham-ts/Pathfinder-2E-Spell-DB/blob/530aabe2013586d57bdba516adc9bbdc1b15ca6c/SpellDB/src/data/spells.json#L5154

Looks like it has the full range info in the JSON & definitely shows up in app. May have been cleaned up in one of the earlier data fixes. Either way I'll close this one.
