### ISSUE TITLE
Any intention of updating the spells.json under the Nethys scrape dir?

### ISSUE THREAD

**Issue by jrmiller82** [fyjham-ts/Pathfinder-2E-Spell-DB#20]

**Comment by fyjham-ts** [comment]
Actually I'll probably remove it once I get around to improving the scrape & connect it direct to the app data file. That one was a staging file to sanity check output. I've got a few goals there before next book with spells is out but atm focusing on vancian casting support.

The updated spell data with manual fixes that the app runs off can be found at SpellDB/src/data/spells.json

**Comment by jrmiller82** [comment]
Thanks! I didn't realize there was a second one!

**Comment by jrmiller82** [comment]
FYI: I'm maintaining a repo on gitlab that is creating a sqlite database of all the PF2 content. We currently use your spells.json to generate the spell tables (until we hard code it to .sql only). You have an acknowledgement in the repo. Come check us out sometime; we're MIT / OGL on licenses too. https://gitlab.com/jrmiller82/pathfinder-2-sqlite

**Comment by fyjham-ts** [comment]
Awesome! Brilliant idea & glad this could help with some of the data!

I'll definitely have to take a look at that SQLite DB - great idea & hopefully a community available data set in a format that's structured and easy to work with helps spawn a number of little apps to make things easier for everyone 👍

**Comment by jrmiller82** [comment]
Thanks! That's my goal; to make OGL / open source app creation easier and faster. :)
