### ISSUE TITLE
Heal is Divine AND Primal

### ISSUE THREAD

**Issue by EndlessRampager** [fyjham-ts/Pathfinder-2E-Spell-DB#22]
Heal is marked as only Divine currently

**Comment by fyjham-ts** [comment]
Thanks, already on top of this one. It's same issue as #21 - fix is already in codebase just waiting for release 1.1 to push it out :)

Fix is already viewable on the web UI - Google Play makes it a tad slow to get a release out for android but I'm waiting on their review atm.
Web UI: https://fyjham-ts.github.io/Pathfinder-2E-Spell-DB/
