### ISSUE TITLE
Maybe add a note about use in spreadsheets?

### ISSUE THREAD

**Issue by imposeren** [fyjham-ts/Pathfinder-2E-Spell-DB#23]
It's possible to use your json database in [google spreadsheets](https://medium.com/@paulgambill/how-to-import-json-data-into-google-spreadsheets-in-less-than-5-minutes-a3fede1a014a). Maybe you should mention this in readme too?

After importing json data to some hidden sheet, this data can be further analysed and adapted with the use of OFFSET/FILTER formulas: [example](https://docs.google.com/spreadsheets/d/15aAAEnQkuK4c_1gJ3iXakk2zzDkt-K250UzkfE6MPYk/edit#gid=112334263&range=A25:AF26) (but in this example json data is "copied and pasted as content" to improve performance of the sheet)

**Comment by fyjham-ts** [comment]
While I'm happy to see you've been using it & am totally cool with you doing this, I don't think I'll be putting explicit packages for reading JSON into the readme. There's just so many options around that & I don't really intend to review their one enough to have confidence I'm happy recommending it.

I've added some notes mentioning that it's in JSON format & is possible to load into spreadsheets & other sources to help people realize it's possible, but I'll leave it to others to find the right too.
