### ISSUE TITLE
Spelling Error in Exploration - Repeat a Spell

### ISSUE THREAD

**Issue by SargntSprinkles** [fyjham-ts/Pathfinder-2E-Spell-DB#26]
The word Sustaining in Sustaining a Spell is misspelled in the Repeat a spell action of the Exploration quick reference.

![Capture+_2019-11-03-16-13-01](https://user-images.githubusercontent.com/3606469/68092042-1173fc80-fe55-11e9-9fc7-088ebddb2609.png)

**Comment by fyjham-ts** [comment]
Have merged in the fix, will release in next update.

**Comment by fyjham-ts** [comment]
I think this was already released previously but it'll be in my new build for sure.
