### ISSUE TITLE
Goodberry it's not updated to the post-errata version

### ISSUE THREAD

**Issue by YellowLugh** [fyjham-ts/Pathfinder-2E-Spell-DB#41]
Goodberry entry still shows the first version of the spell, which is almost completely different from the [actual version](https://2e.aonprd.com/Spells.aspx?ID=473).

![Screenshot_20210322_013138_com fyjham_ts pathfinder_2e_spell_db](https://user-images.githubusercontent.com/81136950/111940825-782ba180-8aae-11eb-81fe-c95f8f591896.png)

![Screenshot_20210322_013204_com hsv freeadblockerbrowser](https://user-images.githubusercontent.com/81136950/111940831-7c57bf00-8aae-11eb-9550-6359a8b44eef.png)

**Comment by fyjham-ts** [comment]
Has been addressed in latest data scrape from Nethys - will push a new build soon.
