### ISSUE TITLE
Maze of Locked Doors (and maybe other spells from Agents of Edgewatch) is missing

### ISSUE THREAD

**Issue by YellowLugh** [fyjham-ts/Pathfinder-2E-Spell-DB#47]
[Maze of Locked Doors](https://2e.aonprd.com/Spells.aspx?ID=822) it's a 7th Level spell from Pathfinder #158: Sixty Feet Under pg. 77.

Maybe other spells from Agents of Edgewatch are missing too.

**Comment by fyjham-ts** [comment]
A lot of newer spells were missing - I've checked & this spell is definitely in with the latest (Along with many from Agents of Edgewatch).

Has been addressed in latest data scrape from Nethys - will push a new build soon.
