### ISSUE TITLE
Core Rulebook spells are poorly scraped

### ISSUE THREAD

**Issue by borg286** [fyjham-ts/Pathfinder-2E-Spell-DB#50]
The core spells seem to have had some parsing errors
https://github.com/fyjham-ts/Pathfinder-2E-Spell-DB/blob/master/NethysScrape/spells.json#L1777
None of the core spells seem to have had their useful metadata populated, and their description seems to have had some delimiter not capture the end of the description as it goes on to capture unwanted stuff.  You might want to revisit the parser.

**Comment by fyjham-ts** [comment]
Too vague to be useful feedback. Definitely aware there's shortcomings, but "Hey fix everything" isn't useful feedback that I can action so I'm closing this.
